services:
  db:
    container_name: "skills_auth_pg"
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    container_name: "skills_auth_redis"
    image: redis:7.4
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app_network
    restart: always
    volumes:
      - redis_data:/data

  localstack:
    container_name: localstack
    environment:
      - SERVICES=${SERVICES}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - LOCALSTACK_HOST=${LOCALSTACK_HOST}
      - DEBUG=${DEBUG}
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    volumes:
      - "localstack_data:/var/lib/localstack"
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:
  localstack_data:

networks:
  app_network:
    driver: bridge
