services:
  localstack:
    container_name: localstack
    environment:
      - SERVICES=${SERVICES}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - LOCALSTACK_HOST=${LOCALSTACK_HOST}
      - DEBUG=${DEBUG}
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    volumes:
      - "localstack_data:/var/lib/localstack"
    networks:
      - app_network

volumes:
  localstack_data:

networks:
  app_network:
    external: true
